spring:
  application:
    name: w2m-disputes

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: w2m-disputes-service
            client-secret: LbBHRR5M6e5XiuTlYBEONGE8yqMurWCq
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://localhost:8181/realms/w2m-disputes/protocol/openid-connect/token

  datasource:
    url: jdbc:postgresql://localhost:5432/disputesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090
