spring:
  application:
    name: w2m-disputes

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: w2m-disputes-service
            client-secret: LbBHRR5M6e5XiuTlYBEONGE8yqMurWCq
            authorization-grant-type: client_credentials
            provider: keycloak
        provider:
          keycloak:
            token-uri: http://localhost:8181/realms/w2m-disputes/protocol/openid-connect/token

  datasource:
    url: jdbc:postgresql://localhost:5432/disputesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

w2m:
  rest:
    client:
      services:
        snowflake-client:
          service-url: http://localhost:8081
          connect-timeout-ms: 1500
          read-timeout-ms: 3000
          max-retries: 0
          oauth2:
            client-id: w2m-disputes-service
            client-registration-id: keycloak
            principal: snowflake-client

server:
  port: 8090
