version: "3.8"

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: mockserve
    ports:
      - "8082:8080"
    volumes:
      - ./volumes/wiremock/mappings:/home/wiremock/mappings
      - ./volumes/wiremock/__files:/home/wiremock/__files

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./volumes/keycloak/keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: